export enum HTTP_STATUS {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  SERVER_ERROR = 500,
}

export type HTTP_STATUS_OPTS =
  | HTTP_STATUS.OK
  | HTTP_STATUS.CREATED
  | HTTP_STATUS.FORBIDDEN
  | HTTP_STATUS.NOT_FOUND
  | HTTP_STATUS.BAD_REQUEST
  | HTTP_STATUS.SERVER_ERROR
  | HTTP_STATUS.UNAUTHORIZED;

export enum METHOD {
  GET = 'get',
  PUT = 'put',
  POST = 'post',
  DELETE = 'delete',
  PATCH = 'patch',
}
